vich_uploader:
    db_driver: orm

    mappings:
        activities:
            uri_prefix: /images/activities
            upload_destination: '%kernel.project_dir%/public/images/activities'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        medias:
            uri_prefix: /images/medias
            upload_destination: '%kernel.project_dir%/public/images/medias'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
